#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "e-commerce-erp"
compatibility_date = "2024-04-01"

[assets]
directory = "./dist"

[build]
command = "npm run build"
